"""Canonical key names, vendored from the ``keyboard`` library.

GENERATED FILE -- do not hand-edit. Regenerate with the script in the repo's
task notes if the pinned ``keyboard`` version ever changes.

Why this exists: ``keyboard`` refuses to import on macOS unless the process is
root, and it resolves key names against the live OS layout. Both are fine on
Windows, where the app actually runs -- but the *portable* half of the project
(``hotkey_spec``, ``config``, ``controller``) has to stay importable and
testable on a Mac, which is where the recorder and the state machine get built.

So the name table is captured from the real library on Windows and committed.
``hotkey_spec`` prefers the live library whenever it can be imported and only
falls back to this table when it cannot, and
``test_vendored_key_table_matches_the_library`` fails on Windows if the two
ever drift apart.
"""

#: Alias -> canonical name (only entries where the two differ).
ALIASES: dict[str, str] = {   '\x08': 'backspace',
    '\t': 'tab',
    '\n': 'enter',
    '\r': 'enter',
    '\x1b': 'esc',
    ' ': 'space',
    'add': '+',
    'altgr': 'alt gr',
    'ampersand': '&',
    'apostrophe': "'",
    'app': 'menu',
    'application': 'menu',
    'applications': 'menu',
    'apps': 'menu',
    'asciicircum': '^',
    'asciitilde': '~',
    'asterisk': '*',
    'at': '@',
    'backslash': '\\',
    'bar': '|',
    'braceleft': '{',
    'braceright': '}',
    'bracketleft': '[',
    'bracketright': ']',
    'capslock': 'caps lock',
    'cmd': 'windows',
    'colon': ':',
    'comma': ',',
    'command': 'windows',
    'control': 'ctrl',
    'ctrll lock': 'caps lock',
    'del': 'delete',
    'dollar': '$',
    'dot': '.',
    'down arrow': 'down',
    'eight': '8',
    'equal': '=',
    'escape': 'esc',
    'exclam': '!',
    'five': '5',
    'four': '4',
    'grave': '`',
    'greater': '>',
    'hash': '#',
    'hashtag': '#',
    'ins': 'insert',
    'left arrow': 'left',
    'left control': 'left ctrl',
    'left menu': 'left alt',
    'left win': 'left windows',
    'less': '<',
    'linefeed': 'enter',
    'minplus': '+',
    'nine': '9',
    'nobreakspace': ' ',
    'num 0': '0',
    'num 1': '1',
    'num 2': '2',
    'num 3': '3',
    'num 4': '4',
    'num 5': '5',
    'num 6': '6',
    'num 7': '7',
    'num 8': '8',
    'num 9': '9',
    'num add': '+',
    'num divide': '/',
    'num enter': 'enter',
    'num minus': '-',
    'num multiply': '*',
    'num plus': '+',
    'num sub': '-',
    'number lock': 'num lock',
    'numbersign': '#',
    'numlock': 'num lock',
    'one': '1',
    'option': 'alt',
    'pagedown': 'page down',
    'pageup': 'page up',
    'parenleft': '(',
    'parenright': ')',
    'pause break': 'pause',
    'percent': '%',
    'period': '.',
    'pgdown': 'page down',
    'pgup': 'page up',
    'play/pause': 'play/pause media',
    'plus': '+',
    'prnt scrn': 'print screen',
    'prtscn': 'print screen',
    'question': '?',
    'quotedbl': '"',
    'quotesingle': "'",
    'return': 'enter',
    'right arrow': 'right',
    'right control': 'right ctrl',
    'right win': 'right windows',
    'scrlk': 'scroll lock',
    'semicolon': ';',
    'seven': '7',
    'six': '6',
    'slash': '/',
    'snapshot': 'print screen',
    'space bar': 'space',
    'spacebar': 'space',
    'subtract': '-',
    'three': '3',
    'til': '~',
    'two': '2',
    'underscore': '_',
    'up arrow': 'up',
    'win': 'windows',
    'zero': '0'}

#: Every key name the Windows layout accepts, canonical spelling.
VALID_NAMES: frozenset[str] = frozenset(
{   '\x03',
    '\x08',
    '\t',
    '\n',
    '\r',
    '\x1b',
    ' ',
    '!',
    '"',
    '#',
    '$',
    '%',
    '&',
    "'",
    '(',
    ')',
    '*',
    '+',
    ',',
    '-',
    '.',
    '/',
    '0',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    ':',
    ';',
    '<',
    '<00>',
    '=',
    '>',
    '?',
    '@',
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'Grave',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
    '[',
    '\\',
    ']',
    '^',
    '_',
    '`',
    'a',
    'add',
    'alt',
    'alt gr',
    'altgr',
    'ampersand',
    'apostrophe',
    'app',
    'application',
    'applications',
    'apps',
    'asciicircum',
    'asciitilde',
    'asterisk',
    'at',
    'attn',
    'b',
    'backslash',
    'backspace',
    'bar',
    'braceleft',
    'braceright',
    'bracketleft',
    'bracketright',
    'break',
    'browser back',
    'browser favorites',
    'browser forward',
    'browser refresh',
    'browser search key',
    'browser start and home',
    'browser stop',
    'c',
    'caps lock',
    'capslock',
    'clear',
    'cmd',
    'colon',
    'comma',
    'command',
    'control',
    'control-break processing',
    'crsel',
    'ctrl',
    'ctrll lock',
    'd',
    'decimal',
    'del',
    'delete',
    'dollar',
    'dot',
    'down',
    'down arrow',
    'e',
    'eight',
    'end',
    'enter',
    'equal',
    'erase eof',
    'esc',
    'escape',
    'exclam',
    'execute',
    'exsel',
    'f',
    'f1',
    'f10',
    'f11',
    'f12',
    'f13',
    'f14',
    'f15',
    'f16',
    'f17',
    'f18',
    'f19',
    'f2',
    'f20',
    'f21',
    'f22',
    'f23',
    'f24',
    'f3',
    'f4',
    'f5',
    'f6',
    'f7',
    'f8',
    'f9',
    'five',
    'four',
    'g',
    'grave',
    'greater',
    'h',
    'hash',
    'hashtag',
    'help',
    'home',
    'i',
    'ime accept',
    'ime convert',
    'ime final mode',
    'ime hangul mode',
    'ime junja mode',
    'ime kanji mode',
    'ime mode change request',
    'ime nonconvert',
    'ime process',
    'ins',
    'insert',
    'j',
    'k',
    'l',
    'left',
    'left alt',
    'left arrow',
    'left control',
    'left ctrl',
    'left menu',
    'left shift',
    'left win',
    'left windows',
    'less',
    'linefeed',
    'm',
    'menu',
    'minplus',
    'n',
    'next track',
    'nine',
    'num *',
    'num +',
    'num -',
    'num /',
    'num 0',
    'num 1',
    'num 2',
    'num 3',
    'num 4',
    'num 5',
    'num 6',
    'num 7',
    'num 8',
    'num 9',
    'num add',
    'num del',
    'num divide',
    'num enter',
    'num lock',
    'num minus',
    'num multiply',
    'num plus',
    'num sub',
    'number lock',
    'numbersign',
    'numlock',
    'o',
    'one',
    'option',
    'p',
    'pa1',
    'page down',
    'page up',
    'pagedown',
    'pageup',
    'parenleft',
    'parenright',
    'pause',
    'pause break',
    'percent',
    'period',
    'pgdown',
    'pgup',
    'play',
    'play/pause',
    'play/pause media',
    'plus',
    'previous track',
    'print',
    'print screen',
    'prnt scrn',
    'prtscn',
    'q',
    'question',
    'quotedbl',
    'quotesingle',
    'r',
    'reserved ',
    'return',
    'right',
    'right alt',
    'right arrow',
    'right control',
    'right ctrl',
    'right menu',
    'right shift',
    'right win',
    'right windows',
    's',
    'scrlk',
    'scroll lock',
    'select',
    'select media',
    'semicolon',
    'separator',
    'seven',
    'shift',
    'six',
    'slash',
    'sleep',
    'snapshot',
    'space',
    'space bar',
    'spacebar',
    'start application 1',
    'start application 2',
    'start mail',
    'stop media',
    'subtract',
    'sys req',
    't',
    'tab',
    'three',
    'til',
    'two',
    'u',
    'underscore',
    'up',
    'up arrow',
    'v',
    'volume down',
    'volume mute',
    'volume up',
    'w',
    'win',
    'windows',
    'x',
    'y',
    'z',
    'zero',
    'zoom',
    '{',
    '|',
    '}',
    '~'}
)
