"""Generate VocalAdvantage.app -- the only macOS launcher with no Terminal.

    python tools/make_mac_app.py

A `.command` file always opens a Terminal window and leaves it sitting there;
macOS gives it no way not to. A bundle is the real answer, and it is also what
can go in System Settings > General > Login Items.

**Grant permissions to the bundle once.** A `.app` is a new TCC identity, so
Accessibility and Microphone have to be allowed for VocalAdvantage.app even
though Terminal already has them. Until that is done the hotkey is dead and
nothing says why -- `hotkey_mac` raises a specific error for exactly this, so
run `python -m vocal_advantage` from a terminal if it seems not to work and
read what it says.

The bundle is a stub: three small files pointing at this checkout. Moving or
renaming the repo breaks it; re-run this to fix it.
"""

from __future__ import annotations

import os
import plistlib
import shutil
import stat
import sys
from pathlib import Path

APP_NAME = "VocalAdvantage"
BUNDLE_ID = "com.kevin.vocal-advantage"

LAUNCHER = """#!/bin/bash
# Generated by tools/make_mac_app.py. Edit that, not this.
cd {repo} || exit 1
exec {python} -m vocal_advantage
"""


def build(repo: Path, python: Path, destination: Path) -> Path:
    bundle = destination / f"{APP_NAME}.app"
    macos = bundle / "Contents" / "MacOS"

    # Rebuilt from scratch each time: a half-updated bundle that still launches
    # the old path is worse than no bundle, because it looks like it worked.
    if bundle.exists():
        shutil.rmtree(bundle)
    macos.mkdir(parents=True)

    plist = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": "Vocal Advantage",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": "0.1.0",
        "CFBundleShortVersionString": "0.1.0",
        "CFBundleExecutable": APP_NAME,
        "CFBundlePackageType": "APPL",
        # No Dock icon, no menu bar of its own. main.py also sets accessory
        # activation policy at runtime; this is the same thing declared up
        # front, so there is no flicker of a Dock icon at launch.
        "LSUIElement": True,
        "LSMinimumSystemVersion": "12.0",
        # macOS shows these strings in the permission prompts, and a bundle
        # without them is denied silently rather than asked about.
        "NSMicrophoneUsageDescription":
            "Vocal Advantage transcribes your speech on this Mac. "
            "Audio never leaves the machine.",
        "NSInputMonitoringUsageDescription":
            "Vocal Advantage watches for the hotkey you chose so you can "
            "hold it to dictate.",
    }
    with open(bundle / "Contents" / "Info.plist", "wb") as handle:
        plistlib.dump(plist, handle)

    script = macos / APP_NAME
    script.write_text(
        LAUNCHER.format(repo=_quote(repo), python=_quote(python)), encoding="utf-8"
    )
    script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return bundle


def _quote(path: Path) -> str:
    """Shell-safe. The repo lives next to a folder with a space in its name."""
    return '"' + str(path).replace('"', '\\"') + '"'


def main(argv: list[str] | None = None) -> int:
    if sys.platform != "darwin":
        print("This only makes sense on macOS.", file=sys.stderr)
        return 1

    repo = Path(__file__).resolve().parent.parent
    venv_python = repo / ".venv" / "bin" / "python"
    python = venv_python if venv_python.exists() else Path(sys.executable)

    bundle = build(repo, python, repo)

    print(f"Built {bundle}")
    print(f"  runs: {python} -m vocal_advantage")
    print("")
    print("Double-click it once. macOS will ask for Microphone permission, and")
    print("the hotkey needs Accessibility -- System Settings > Privacy &")
    print("Security > Accessibility -- granted to VocalAdvantage.app itself,")
    print("even though Terminal already has it.")
    print("")
    print("To start it at login: System Settings > General > Login Items.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
